// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9l2aGXWaz-ErAAyODwBzHc_pHITfHcy0',
    appId: '1:1081616661628:android:98398968f521260b955df9',
    messagingSenderId: '1081616661628',
    projectId: 'lieary2',
    storageBucket: 'lieary2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR5owVszA9N_pGY-692g3s2BTQB3cbQFI',
    appId: '1:1081616661628:ios:ee10e33aec6d1d17955df9',
    messagingSenderId: '1081616661628',
    projectId: 'lieary2',
    storageBucket: 'lieary2.appspot.com',
    androidClientId: '1081616661628-5kc4psmg1n5s17sv573fo47vgdip63sg.apps.googleusercontent.com',
    iosClientId: '1081616661628-1ihepten4dmbnesfpaukfvjaap6pcp7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
